spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: c202_api
    url: jdbc:mysql://j9c202.p.ssafy.io:3306/asap_api
    password: '!asap1290!@()'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  profiles:
    active: local

  data:
    redis:
      host: j9c202.p.ssafy.io
      password: asap123!@#
      port: 6379

server:
  port: '9001'


ethereum:
  server:
    ip: localhost
    port: 8545